{{define "top"}}// This file has been automatically generated by goFB
// Compiler written by Hammond Pearce and available at github.com/kiwih/goFB
{{$block := index .Blocks .BlockIndex}}{{$blocks := .Blocks}}
//This is the main file for the iec61499 network with {{$block.Name}} as the top level block

#include "{{$block.Name}}.h"

//TODO: replace all this with an invocation queue

//there will also be the emit function definition 

//the emit function will take an event ID and place the appropriate invocations onto the invocation queue

//put a copy of the top level block into global memory

/* event_[ID]_run() executes a single event from the event
 * queue. Notice that it does not perform any computation nor create any 
 * additional events.
 */
void event_{{$eventID}}_run({{$block.Type}}_t *me) {
	//for every eventID
		//for every block this invokes
			//set input event flag
			//copy associated input data from source data
			//invoke function using x_instance_x_run() function
				//enqueue emitted events
}

{{/* We need to know about every instance of every fb in the network 
   * so that we can create their invokation function.
   * Invokation functions are necessary so that we can enqueue events that they emit
   */}}

//for every block inside this block
	//if composite, recurse
	//if basic, create invokation function

{{range $currChildIndex, $child := $block.CompositeFB.FBs}}
/* {{$block.Name}}_instance_{{$child.Name}}_run() executes a single invokation of 
 * {{$child.Name}} (which is an instance of {{$child.Type}}) according to 
 * IEC61499 event-driven semantics.
 * Notice that it does NOT perform any I/O - synchronisation
 * is done using the event function at this level.
 */
void {{$block.Name}}_instance_{{$child.Name}}_run({{$child.Type}}_t *inst, int eventID) {

}





{{$block.Name}}_t my{{$block.Name}};

int main() {
	if({{$block.Name}}_preinit(&my{{$block.Name}}) != 0) {
		printf("Failed to preinitialize.");
		return 1;
	}
	if({{$block.Name}}_init(&my{{$block.Name}}) != 0) {
		printf("Failed to initialize.");
		return 1;
	}

	printf("Top: %20s   Size: %lu\n", "{{$block.Name}}", sizeof(my{{$block.Name}}));

	int tickNum = 0;
	do {
		//printf("=====TICK %i=====\n",tickNum);
		{{$block.Name}}_syncOutputEvents(&my{{$block.Name}});
		{{$block.Name}}_syncInputEvents(&my{{$block.Name}});

		{{$block.Name}}_syncOutputData(&my{{$block.Name}});
		{{$block.Name}}_syncInputData(&my{{$block.Name}});
		
		{{$block.Name}}_run(&my{{$block.Name}});
	} while(tickNum++ < 500);

	return 0;
}

{{end}}