// This file is generated by FBC.

#ifndef _CORESINGLE_H_
#define _CORESINGLE_H_

#include "fbtypes.h"
#include "SawmillModule.h"
#include "PrintStatus.h"

typedef struct {
    SawmillModule saw1;
    SawmillModule saw2;
    SawmillModule saw3;
    PrintStatus statusprint;
} _CoreSingle;

/* Function block initialization function */
void _CoreSingleinit(_CoreSingle* me);

/* Function block execution function */
void _CoreSinglerun(_CoreSingle* me);

#endif // _CORESINGLE_H_
