// This file is generated by FBC.

#ifndef PRINTSTATUS_H_
#define PRINTSTATUS_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT StatusUpdate : 1; // 
    } event;
} PrintStatusIEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    PrintStatusIEvents _input;
    INT Saw1Status; // 
    INT _Saw1Status;
    INT Saw2Status; // 
    INT _Saw2Status;
    INT Saw3Status; // 
    INT _Saw3Status;
} PrintStatus;

/* Function block initialization function */
void PrintStatusinit(PrintStatus* me);

/* Function block execution function */
void PrintStatusrun(PrintStatus* me);

/* ECC algorithms */
void PrintStatus_PrintService(PrintStatus* me);

#endif // PRINTSTATUS_H_
