// This file is generated by FBC.

#ifndef SAWMILLSPEED_H_
#define SAWMILLSPEED_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT NewPos : 1; // 
    } event;
} SawmillSpeedIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT BadSpeedChange : 1; // 
    } event;
} SawmillSpeedOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    SawmillSpeedIEvents _input;
    LREAL Pos; // 
    LREAL _Pos;
    SawmillSpeedOEvents _output;
    BOOL BadSpeed; // 
    BOOL _BadSpeed;
    LREAL LastPos; // 
} SawmillSpeed;

/* Function block initialization function */
void SawmillSpeedinit(SawmillSpeed* me);

/* Function block execution function */
void SawmillSpeedrun(SawmillSpeed* me);

/* ECC algorithms */
void SawmillSpeed_speedChange_service(SawmillSpeed* me);

#endif // SAWMILLSPEED_H_
