// This file is generated by FBC.

#ifndef SAWMILLCONTROL_H_
#define SAWMILLCONTROL_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT ControlChange : 1; // 
        UDINT WeightChange : 1; // 
        UDINT LaserChange : 1; // 
        UDINT BadSpeedChange : 1; // 
        UDINT StallDetectedChange : 1; // 
    } event;
} SawmillControlIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT CommandChange : 1; // 
        UDINT MessageChange : 1; // 
    } event;
} SawmillControlOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    SawmillControlIEvents _input;
    BOOL ControlRun; // 
    BOOL _ControlRun;
    BOOL ScaleOverweight; // 
    BOOL _ScaleOverweight;
    BOOL LaserBroken; // 
    BOOL _LaserBroken;
    BOOL BadSpeed; // 
    BOOL _BadSpeed;
    BOOL StallDetected; // 
    BOOL _StallDetected;
    SawmillControlOEvents _output;
    BOOL SawRun; // 
    BOOL _SawRun;
    INT Message; // 
    INT _Message;
} SawmillControl;

/* Function block initialization function */
void SawmillControlinit(SawmillControl* me);

/* Function block execution function */
void SawmillControlrun(SawmillControl* me);

/* ECC algorithms */
void SawmillControl_MessageHaltWeight(SawmillControl* me);
void SawmillControl_MessageHaltLaser(SawmillControl* me);
void SawmillControl_MessageRun(SawmillControl* me);
void SawmillControl_MessageStop(SawmillControl* me);
void SawmillControl_SawRun(SawmillControl* me);
void SawmillControl_SawStop(SawmillControl* me);
void SawmillControl_MessageBadSpeed(SawmillControl* me);
void SawmillControl_MessageStallDetected(SawmillControl* me);

#endif // SAWMILLCONTROL_H_
