// This file is generated by FBC.

#include "c0__Core0.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void c0__Core0init(c0__Core0* me)
{
    ArgoRxinit(&me->saw1rx);
    ArgoRxinit(&me->saw2rx);
    ArgoRxinit(&me->saw3rx);
    PrintStatusinit(&me->statusprint);
    me->saw1rx._ChanId = 1;
    me->saw2rx._ChanId = 2;
    me->saw3rx._ChanId = 3;

    ArgoRxchaninit(&me->saw1rx);
    ArgoRxchaninit(&me->saw2rx);
    ArgoRxchaninit(&me->saw3rx);
}

/* Function block execution function */
void c0__Core0run(c0__Core0* me)
{
    me->statusprint._Saw2Status = me->saw2rx._Data;
    me->statusprint._input.event.StatusUpdate = me->saw2rx._output.event.DataPresent || me->saw1rx._output.event.DataPresent || me->saw3rx._output.event.DataPresent;
    me->statusprint._Saw1Status = me->saw1rx._Data;
    me->statusprint._Saw3Status = me->saw3rx._Data;
    
    ArgoRxrun(&me->saw1rx);
    ArgoRxrun(&me->saw2rx);
    ArgoRxrun(&me->saw3rx);
    PrintStatusrun(&me->statusprint);
    
}
