// This file is generated by FBC.

#ifndef C0__CORE0_H_
#define C0__CORE0_H_

#include "fbtypes.h"
#include "ArgoRx.h"
#include "PrintStatus.h"

typedef struct {
    ArgoRx saw1rx;
    ArgoRx saw2rx;
    ArgoRx saw3rx;
    PrintStatus statusprint;
} c0__Core0;

/* Function block initialization function */
void c0__Core0init(c0__Core0* me);

/* Function block execution function */
void c0__Core0run(c0__Core0* me);

#endif // C0__CORE0_H_
