// This file is generated by FBC.

#ifndef C1__CORE1_H_
#define C1__CORE1_H_

#include "fbtypes.h"
#include "SawmillModule.h"
#include "SawmillMessageHandler.h"
#include "ArgoTx.h"

typedef struct {
    SawmillModule sawmill;
    SawmillMessageHandler messageHandler;
    ArgoTx tx;
} c1__Core1;

/* Function block initialization function */
void c1__Core1init(c1__Core1* me);

/* Function block execution function */
void c1__Core1run(c1__Core1* me);

#endif // C1__CORE1_H_
