// This file is generated by FBC.

#include "c1__Core1.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void c1__Core1init(c1__Core1* me)
{
    SawmillModuleinit(&me->sawmill);
    SawmillMessageHandlerinit(&me->messageHandler);
    ArgoTxinit(&me->tx);
    me->tx._ChanId = 1;
    
    ArgoTxchaninit(&me->tx);
}

/* Function block execution function */
void c1__Core1run(c1__Core1* me)
{
    me->messageHandler._TxSuccess = me->tx._Success;
    me->messageHandler._input.event.MessageChanged = me->sawmill._output.event.MessageChange;
    me->messageHandler._Message = me->sawmill._Message;
    me->messageHandler._input.event.TxSuccessChanged = me->tx._output.event.SuccessChanged;
    me->tx._input.event.DataPresent = me->messageHandler._output.event.TxDataPresent;
    me->tx._Data = me->messageHandler._TxData;
    
    SawmillModulerun(&me->sawmill);
    SawmillMessageHandlerrun(&me->messageHandler);
    ArgoTxrun(&me->tx);
    
}
