// This file is generated by FBC.

#ifndef C3__CORE3_H_
#define C3__CORE3_H_

#include "fbtypes.h"
#include "ArgoTx.h"
#include "SawmillMessageHandler.h"
#include "SawmillModule.h"

typedef struct {
    ArgoTx tx;
    SawmillMessageHandler messageHandler;
    SawmillModule sawmill;
} c3__Core3;

/* Function block initialization function */
void c3__Core3init(c3__Core3* me);

/* Function block execution function */
void c3__Core3run(c3__Core3* me);

#endif // C3__CORE3_H_
