// This file is generated by FBC.

#ifndef LED_H_
#define LED_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT CommandChange : 1; // 
    } event;
} LedIEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    LedIEvents _input;
    BOOL Run; // 
    BOOL _Run;
} Led;

/* Function block initialization function */
void Ledinit(Led* me);

/* Function block execution function */
void Ledrun(Led* me);

/* ECC algorithms */
void Led_LedService(Led* me);

#endif // LED_H_
