// This file is generated by FBC.

#include "Led.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void Ledinit(Led* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
}

/* ECC algorithms */
void Led_LedService(Led* me)
{
if(me->_input.event.CommandChange) {
 LED = me->Run;
}
}

/* Function block execution function */
void Ledrun(Led* me)
{
    
    if (me->_input.event.CommandChange) {
        me->Run = me->_Run;
    }
    for (;;) {
        if (me->_state == 0) {
            // State: Start
            if (!me->_entered) {
                me->_entered = true;
            }
            else {
                me->_state = 1;
                me->_entered = false;
                continue;
            }
        }
        else {
            // State: Run
            if (!me->_entered) {
                Led_LedService(me);
                me->_entered = true;
            }
            else {
                me->_state = 1;
                me->_entered = false;
                continue;
            }
        }
        break;
    }
    me->_input.events = 0;
}

