// This file is generated by FBC.

#ifndef MASKEDSWITCH_H_
#define MASKEDSWITCH_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT SwitchChanged : 1; // 
    } event;
} MaskedSwitchOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    BYTE SwitchMask; // 
    BYTE _SwitchMask;
    MaskedSwitchOEvents _output;
    BOOL SwitchOn; // 
    BOOL _SwitchOn;
} MaskedSwitch;

/* Function block initialization function */
void MaskedSwitchinit(MaskedSwitch* me);

/* Function block execution function */
void MaskedSwitchrun(MaskedSwitch* me);

/* ECC algorithms */
void MaskedSwitch_SwitchesService(MaskedSwitch* me);

#endif // MASKEDSWITCH_H_
