// This file is generated by FBC.

#ifndef SAWMILLMODULE_H_
#define SAWMILLMODULE_H_

#include "fbtypes.h"
#include "Led.h"
#include "SawmillControl.h"
#include "MaskedSwitch.h"
#include "SawmillSpeed.h"
#include "SawmillPosGen.h"

typedef union {
    UDINT events;
    struct {
        UDINT MessageChange : 1; // 
    } event;
} SawmillModuleOEvents;

typedef struct {
    SawmillModuleOEvents _output;
    INT _Message;
    Led saw;
    SawmillControl control;
    MaskedSwitch runswitch;
    MaskedSwitch scale;
    MaskedSwitch laser;
    SawmillSpeed speedmon;
    SawmillPosGen posgen;
    MaskedSwitch stall;
} SawmillModule;

/* Function block initialization function */
void SawmillModuleinit(SawmillModule* me);

/* Function block execution function */
void SawmillModulerun(SawmillModule* me);

#endif // SAWMILLMODULE_H_
