// This file is generated by FBC.

#include "SawmillSpeed.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void SawmillSpeedinit(SawmillSpeed* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
}

/* ECC algorithms */
void SawmillSpeed_speedChange_service(SawmillSpeed* me) {
if(me->LastPos != 0) {
	REAL diff = 0;
	diff = me->Pos - me->LastPos;
	if(diff < 0) { //make diff positive if it is negative
		diff = diff * -1; 
	}

	//do some math to emulate a computationally difficult task
	int x = (int)diff;
	#pragma loopbound min 1 max 1000
	for(int y = 0; y<1000; y++) {
		x = x * 2;
		x = x + 1;
	} 

	if(diff > 2 && x != 0) {
		me->_output.event.BadSpeedChange = 1;
		me->BadSpeed = true;
	} else {
		me->_output.event.BadSpeedChange = 1;
		me->BadSpeed = false;
	}
}

me->LastPos = me->Pos;
}

/* Function block execution function */
void SawmillSpeedrun(SawmillSpeed* me)
{
    me->_output.events = 0;

    if (me->_input.event.NewPos) {
        me->Pos = me->_Pos;
    }
    for (;;) {
        if (me->_state == 0) {
            // State: Start
            if (!me->_entered) {
                me->_entered = true;
            }
            else {
                me->_state = 1;
                me->_entered = false;
                continue;
            }
        }
        else {
            // State: Run
            if (!me->_entered) {
                SawmillSpeed_speedChange_service(me);
                me->_entered = true;
            }
            else {
                if (me->_input.event.NewPos) {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        break;
    }
    if (me->_output.event.BadSpeedChange) {
        me->_BadSpeed = me->BadSpeed;
    }

    me->_input.events = 0;
}

