// This file is generated by FBC.

#include "SawmillModule.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void SawmillModuleinit(SawmillModule* me)
{
    me->_output.events = 0;
    Ledinit(&me->saw);
    SawmillControlinit(&me->control);
    MaskedSwitchinit(&me->runswitch);
    MaskedSwitchinit(&me->scale);
    MaskedSwitchinit(&me->laser);
    SawmillSpeedinit(&me->speedmon);
    SawmillPosGeninit(&me->posgen);
    MaskedSwitchinit(&me->stall);
    me->runswitch._SwitchMask = 0b0001;
    me->scale._SwitchMask = 0b0010;
    me->laser._SwitchMask = 0b0100;
    me->stall._SwitchMask = 0b1000;
}

/* Function block execution function */
void SawmillModulerun(SawmillModule* me)
{
    me->saw._Run = me->control._SawRun;
    me->saw._input.event.CommandChange = me->control._output.event.CommandChange;
    me->control._ControlRun = me->runswitch._SwitchOn;
    me->control._input.event.WeightChange = me->scale._output.event.SwitchChanged;
    me->control._input.event.BadSpeedChange = me->speedmon._output.event.BadSpeedChange;
    me->control._input.event.ControlChange = me->runswitch._output.event.SwitchChanged;
    me->control._input.event.StallDetectedChange = me->stall._output.event.SwitchChanged;
    me->control._input.event.LaserChange = me->laser._output.event.SwitchChanged;
    me->control._StallDetected = me->stall._SwitchOn;
    me->control._ScaleOverweight = me->scale._SwitchOn;
    me->control._LaserBroken = me->laser._SwitchOn;
    me->control._BadSpeed = me->speedmon._BadSpeed;
    me->speedmon._Pos = me->posgen._NewPos;
    me->speedmon._input.event.NewPos = me->posgen._output.event.NewPosChange;
    me->posgen._SawRun = me->control._SawRun;
    me->posgen._input.event.SawRunChange = me->control._output.event.CommandChange;
    
    Ledrun(&me->saw);
    SawmillControlrun(&me->control);
    MaskedSwitchrun(&me->runswitch);
    MaskedSwitchrun(&me->scale);
    MaskedSwitchrun(&me->laser);
    SawmillSpeedrun(&me->speedmon);
    SawmillPosGenrun(&me->posgen);
    MaskedSwitchrun(&me->stall);
    
    me->_Message = me->control._Message;
    me->_output.event.MessageChange = me->control._output.event.MessageChange;
}
